// rf_top.cpp — Top-level for BRAM-based Random Forest
// =====================================================
// Compatible with BRAM node-array trees generated by jsontoh.py
// BUG 1 FIX: reset port flushes temporal window between test samples

#include "rf_eeg.h"
#include "trees.h"

label_t rf_top(
    const feature_t features[NUM_FEATURES],
    reset_t         reset
) {
	// --- THE FIX: Change interfaces to AXI4-Lite ---
	    #pragma HLS INTERFACE s_axilite port=return bundle=CTRL
	    #pragma HLS INTERFACE s_axilite port=reset bundle=CTRL
	    #pragma HLS INTERFACE s_axilite port=features bundle=CTRL
#pragma HLS ARRAY_PARTITION variable=features complete dim=1

    // ── Temporal fusion sliding window ────────────────────────────────────
    static label_t   window[WINDOW_SIZE];
    static ap_uint<3> win_idx  = 0;
    static ap_uint<3> win_fill = 0;

#pragma HLS RESET variable=window
#pragma HLS RESET variable=win_idx
#pragma HLS RESET variable=win_fill

    // ── Reset path ────────────────────────────────────────────────────────
    if (reset == 1) {
        RESET_LOOP: for (int i = 0; i < WINDOW_SIZE; i++) {
#pragma HLS UNROLL
            window[i] = 0;
        }
        win_idx  = 0;
        win_fill = 0;
        return (label_t)0;
    }

    // ── Inference ─────────────────────────────────────────────────────────
    label_t raw_pred = (label_t)rf_predict(features);

    // ── Temporal fusion ───────────────────────────────────────────────────
    window[win_idx] = raw_pred;
    win_idx  = (ap_uint<3>)((win_idx  + 1) % WINDOW_SIZE);
    win_fill = (ap_uint<3>)((win_fill < (ap_uint<3>)WINDOW_SIZE) ?
               (ap_uint<3>)(win_fill + 1) : (ap_uint<3>)WINDOW_SIZE);

    vote_t votes = 0;
    VOTE_LOOP: for (int i = 0; i < WINDOW_SIZE; i++) {
#pragma HLS UNROLL
        if (i < (int)win_fill)
            votes += (window[i] == 1) ? (vote_t)1 : (vote_t)-1;
    }

    return (label_t)(votes > 0 ? 1 : 0);
}
