// trees.h — AUTO-GENERATED by json_to_trees.py
#ifndef TREES_H
#define TREES_H
#include "rf_eeg.h"

int tree_0(const feature_t feat[NUM_FEATURES]);
int tree_1(const feature_t feat[NUM_FEATURES]);
int tree_2(const feature_t feat[NUM_FEATURES]);
int tree_3(const feature_t feat[NUM_FEATURES]);
int tree_4(const feature_t feat[NUM_FEATURES]);
int tree_5(const feature_t feat[NUM_FEATURES]);
int tree_6(const feature_t feat[NUM_FEATURES]);
int tree_7(const feature_t feat[NUM_FEATURES]);
int tree_8(const feature_t feat[NUM_FEATURES]);
int tree_9(const feature_t feat[NUM_FEATURES]);
int tree_10(const feature_t feat[NUM_FEATURES]);
int tree_11(const feature_t feat[NUM_FEATURES]);
int tree_12(const feature_t feat[NUM_FEATURES]);
int tree_13(const feature_t feat[NUM_FEATURES]);
int tree_14(const feature_t feat[NUM_FEATURES]);
int tree_15(const feature_t feat[NUM_FEATURES]);
int tree_16(const feature_t feat[NUM_FEATURES]);
int tree_17(const feature_t feat[NUM_FEATURES]);
int tree_18(const feature_t feat[NUM_FEATURES]);
int tree_19(const feature_t feat[NUM_FEATURES]);
int tree_20(const feature_t feat[NUM_FEATURES]);
int tree_21(const feature_t feat[NUM_FEATURES]);
int tree_22(const feature_t feat[NUM_FEATURES]);
int tree_23(const feature_t feat[NUM_FEATURES]);
int tree_24(const feature_t feat[NUM_FEATURES]);
int tree_25(const feature_t feat[NUM_FEATURES]);
int tree_26(const feature_t feat[NUM_FEATURES]);
int tree_27(const feature_t feat[NUM_FEATURES]);
int tree_28(const feature_t feat[NUM_FEATURES]);
int tree_29(const feature_t feat[NUM_FEATURES]);
int tree_30(const feature_t feat[NUM_FEATURES]);

int rf_predict(const feature_t feat[NUM_FEATURES]);

#endif // TREES_H